name: Docker Hub

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
