name: Docker Hub

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    if: github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build --tag 10up/wpsnapshots --build-arg WPSNAPSHOTS_VERSION ./docker
        env:
          WPSNAPSHOTS_VERSION: ${{ github.event.release.name }}
      - name: Tag Images
        run: |
          docker tag 10up/wpsnapshots 10up/wpsnapshots:${WPSNAPSHOTS_VERSION:0:1}
          docker tag 10up/wpsnapshots 10up/wpsnapshots:${WPSNAPSHOTS_VERSION}
        env:
          WPSNAPSHOTS_VERSION: ${{ github.event.release.name }}
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Images
        run: |
          docker push 10up/wpsnapshots:latest
          docker push 10up/wpsnapshots:${WPSNAPSHOTS_VERSION:0:1}
          docker push 10up/wpsnapshots:${WPSNAPSHOTS_VERSION}
        env:
          WPSNAPSHOTS_VERSION: ${{ github.event.release.name }}
